name:  todo_list
description:  A sample application

dependencies:
  web_ui: '<0.4.3'
  browser: '<0.4.3'
  # limit versions to <0.4.3 for transitive dependencies
  args: '<0.4.3'
  logging: '<0.4.3'
  unittest: '<0.4.3'
  analyzer_experimental: '<0.4.3'
  meta: '<0.4.3'
  pathos: '<0.4.3'

environment:
  sdk: "<0.4.3"