name:  todo_list
description:  A sample application

dependencies:
  web_ui: '<0.4.4'
  browser: '<0.4.4'
  # limit versions to <0.4.4 for transitive dependencies
  args: '<0.4.4'
  logging: '<0.4.4'
  unittest: '<0.4.4'
  analyzer_experimental: '<0.4.4'
  meta: '<0.4.4'
  pathos: '<0.4.4'
