name:  todo_list
description:  A sample application

dependencies:
  web_ui: '<0.4.8'
  browser: '<0.4.8'
  # limit versions to <0.4.8 for transitive dependencies
  #args: '<0.4.8'
  #logging: '<0.4.8'
  #unittest: '<0.4.8'
  #analyzer_experimental: '<0.4.8'
  #meta: '<0.4.8'
  #pathos: '<0.4.8'

environment:
  sdk: "<0.4.8"