name:  todo_list
description:  A sample application

dependencies:
  web_ui: '<0.5.1'
  browser: '<0.5.1'
  # limit versions to <0.5.1 for transitive dependencies
  #args: '<0.5.1'
  #logging: '<0.5.1'
  #unittest: '<0.5.1'
  #analyzer_experimental: '<0.5.1'
  #meta: '<0.5.1'
  #pathos: '<0.5.1'

environment:
  sdk: "<0.5.1"