name:  todo_list
description:  A sample application

dependencies:
  web_ui: '<0.4.2'
  browser: '<0.4.2'
  # limit versions to <0.4.2 for transitive dependencies
  args: '<0.4.2'
  logging: '<0.4.2'
  unittest: '<0.4.2'
  analyzer_experimental: '<0.4.2'
  meta: '<0.4.2'
  pathos: '<0.4.2'

environment:
  sdk: "<0.4.2"